### ISSUE TITLE
a question out of curiasity

### ISSUE THREAD

**Issue by imkarimkarim** [PrivacyForge/ChatGuard#22]
what's your take on messangers that has build with the support of IRI?
and why you first supporte those instead of whatsapp? or other messangers that are more popular in the globe?
im considering to contribute on this project and i really like the idea. but seing the name of apps like bale, soroush, etc... kinda turned me off...

i like to here more about your point of view.
and thanks for you time🙏🏾.

**Comment by imkarimkarim** [comment]
actually when i re-think it i can find a reasonable response to my question. but i like to heare from you guys first :))

**Comment by mostafa-kheibary** [comment]
I initially supported Telegram Messenger, and after that, I looked for messengers with a similar front end, like Bale and Soroush, which have an interface identical to Telegram's. This made it easy for me to port them.

I really want to support other platforms like Weechat, WhatsApp, Instagram, or even Discord. Another reason is that these messengers don’t have proper encryption. I want to support them so that people who are forced to use these applications can feel safe and use them freely without privacy concerns.

**Comment by imkarimkarim** [comment]
@mostafa-kheibary

that's totally reasonable. actually thats what came to my mind too after a little bit of "re-think".
i really like what you guys are doing here and looking forward to help where ever i can. i will watch github issues for the issue i am capabale of participating. 

mean while there are two other things that i like to share with you:

1. i suggest create a project(task board) so there will be more option to choose from when someone wan'ts to contribute.

2. how about pictures, videos and other medias? is it possible/logical to encrypt them too? is there any plan for this problem?

**Comment by mostafa-kheibary** [comment]
Thanks for the suggestion
Yes we have public trello board, you can join as a member with the link below

Also you can email me to be in contact with suggestion or new features that you want to work on
and if you have any question about the project im available.

https://trello.com/invite/b/MQzcGAHU/ATTIaadb78e0fd8b3a0307168a00e853835b25AE7047/main-workflow

**Comment by imkarimkarim** [comment]
couldn't get better. thank you.
